name: Scrape and Push Data

on:
  schedule:
    - cron: '1 7 * * *'   # 每天下午 15:01（北京时间）
  workflow_dispatch:       # 支持手动运行

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python stock_scraper/main.py

      - name: Commit and push updates
        run: |
          git config --global user.email "2627768814@qq.com"
          git config --global user.name "yananit"
          git add .
          git commit -m "自动抓取并更新 Excel"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
