name: Scrape and Push Data

on:
  schedule:
    - cron: '1 7 * * *'  # 每天 15:01 (北京时间)
  workflow_dispatch:      # 允许手动触发

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python stock_scraper/main.py

    - name: Commit and Push Excel
      run: |
        git config --global user.email "2627768814@qq.com"
        git config --global user.name "yananit"
        git add D:/Thszt/*.xlsx || true
        git commit -m "Auto update Excel" || echo "Nothing to commit"
        git push

